# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('Data.csv')
dataset

   Country   Age   Salary Surgery Payment
0   France  44.0  72000.0              No
1    Spain  27.0  48000.0             Yes
2  Germany  30.0  54000.0              No
3    Spain  38.0  61000.0              No
4  Germany  40.0      NaN             Yes
5   France  35.0  58000.0             Yes
6    Spain   NaN  52000.0              No
7   France  48.0  79000.0             Yes
8  Germany  50.0  83000.0              No
9   France  37.0  67000.0             Yes

In [ ]:
dataset.shape

(10, 4)

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
dataset

   Country   Age   Salary Surgery Payment
0   France  44.0  72000.0              No
1    Spain  27.0  48000.0             Yes
2  Germany  30.0  54000.0              No
3    Spain  38.0  61000.0              No
4  Germany  40.0      NaN             Yes
5   France  35.0  58000.0             Yes
6    Spain   NaN  52000.0              No
7   France  48.0  79000.0             Yes
8  Germany  50.0  83000.0              No
9   France  37.0  67000.0             Yes

x = independent variables\
y = dependent variable or target variable

df.iloc[rows, columns]

In [ ]:

x = dataset.iloc[:, :3].values
y= dataset.iloc[:, -1].values

In [ ]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = "mean")
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

remainder= 'passthrough': This means all other columns will remain unchanged (instead of being dropped).

In [ ]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 10)

In [ ]:
x_train

array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
print(x_test)

[[0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 30.0 54000.0]]

In [ ]:
print(y_train)

[1 0 0 1 0 1 1 1]

In [ ]:
print(y_test)

[0 0]

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[1.0 0.0 0.0 -0.5978808481167128 -0.4821493411193374]
 [0.0 0.0 1.0 0.05261351463427101 -1.1114197802841528]
 [0.0 0.0 1.0 -0.08131179534387283 -0.16751412153692968]
 [0.0 0.0 1.0 -1.9753983221776195 -1.5309334063940296]
 [1.0 0.0 0.0 0.9518263102018072 0.9861483502652318]
 [1.0 0.0 0.0 1.6405850472322605 1.7202971959575164]
 [0.0 1.0 0.0 0.2630675731713538 0.12381478548381851]
 [1.0 0.0 0.0 -0.25350147960148617 0.4617563176278857]]

In [ ]:
print(x_test)

[[0.0 1.0 0.0 1.0 1.0]
 [0.0 1.0 0.0 -1.0 -1.0]]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x_train[:, 3:] = scaler.fit_transform(x_train[:, 3:])
x_test[:, 3:] = scaler.transform(x_test[:, 3:])

In [ ]:
x_train

array([[1.0, 0.0, 0.0, 0.38095238095238093, 0.3225806451612905],
       [0.0, 0.0, 1.0, 0.5608465608465609, 0.12903225806451624],
       [0.0, 0.0, 1.0, 0.5238095238095237, 0.4193548387096775],
       [0.0, 0.0, 1.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.8095238095238093, 0.774193548387097],
       [1.0, 0.0, 0.0, 1.0, 1.0],
       [0.0, 1.0, 0.0, 0.6190476190476191, 0.5089605734767026],
       [1.0, 0.0, 0.0, 0.4761904761904763, 0.612903225806452]],
      dtype=object)

**Standard Scaler:** Values are centered around 0, some will be negative, some positive.

When to use: Good if your data has outliers(skewed distribution) or is normally distributed.

**MinMaxScaler:** It rescales all values to a fixed range (usually 0 to 1).
Effect: Smallest value becomes 0, largest becomes 1, everything else fits between.

When to use: Good when you know the bounds and want all features in the same scale.